


<CFSET ASSESSMENT_AMOUNT_UPPER_DisplayAmt = "">


<CFIF ASSESSMENT_AMOUNT_UPPER NEQ "">

	<CFSET ASSESSMENT_AMOUNT_UPPER_DisplayAmt = ASSESSMENT_AMOUNT_UPPER / 1000000>

	<CFSET ASSESSMENT_AMOUNT_UPPER_DisplayAmt = NumberFormat(ASSESSMENT_AMOUNT_UPPER_DisplayAmt, '_$__._') & " Million">

<CFELSE>
	
	<CFSET ASSESSMENT_AMT_MAX_UNKNOWN_Word = "_____">

	<CFLOOP INDEX="ASSESSMENT_AMT_MAX_UNKNOWN_Index" FROM="1" TO="1">

		<CFIF ASSESSMENT_AMT_MAX_UNKNOWN EQ ASSESSMENT_AMT_MAX_UNKNOWN_Index>
			<CFSET ASSESSMENT_AMT_MAX_UNKNOWN_Word = "[" & ListGetAt(Unknown_NA_List, ASSESSMENT_AMT_MAX_UNKNOWN_Index) & "]">
		</cfif>

	</cfloop>

	<CFSET ASSESSMENT_AMOUNT_UPPER_DisplayAmt = ASSESSMENT_AMT_MAX_UNKNOWN_Word>

</cfif>


<CFIF ASSESSMENT_AMT_UPPER_HIGH_END NEQ "">

	<CFSET ASSESSMENT_AMT_UPPER_HIGH_END_DisplayAmt = ASSESSMENT_AMT_UPPER_HIGH_END / 1000000>
	<CFSET ASSESSMENT_AMT_UPPER_HIGH_END_DisplayAmt = NumberFormat(ASSESSMENT_AMT_UPPER_HIGH_END_DisplayAmt, '_$__._') & " Million">
   	<CFSET ASSESSMENT_AMOUNT_UPPER_DisplayAmt = ASSESSMENT_AMOUNT_UPPER_DisplayAmt & " - " & ASSESSMENT_AMT_UPPER_HIGH_END_DisplayAmt>

</cfif>



