
<CFSET Prev_ASSESSMENT_AMOUNT_UPPER_DisplayAmt = "">

<CFIF ThisReportDate NEQ EarliestReportDate AND PrevReportDate NEQ "">

	<CFIF CONTINGENT_LIAB_GetRecord_PrevRpt.ASSESSMENT_AMOUNT_UPPER NEQ "">

		<CFSET Prev_ASSESSMENT_AMOUNT_UPPER_DisplayAmt = CONTINGENT_LIAB_GetRecord_PrevRpt.ASSESSMENT_AMOUNT_UPPER / 1000000>
		<CFSET Prev_ASSESSMENT_AMOUNT_UPPER_DisplayAmt = NumberFormat(Prev_ASSESSMENT_AMOUNT_UPPER_DisplayAmt, '_$__._') & " Million">

	<CFELSE>

		<CFIF CONTINGENT_LIAB_GetRecord_PrevRpt.ASSESSMENT_AMT_MAX_UNKNOWN NEQ "" AND CONTINGENT_LIAB_GetRecord_PrevRpt.ASSESSMENT_AMT_MAX_UNKNOWN NEQ 0>

			<CFLOOP INDEX="Prev_ASSESSMENT_AMT_MAX_UNKNOWN_Index" FROM="1" TO="1">

				<CFIF CONTINGENT_LIAB_GetRecord_PrevRpt.ASSESSMENT_AMT_MAX_UNKNOWN EQ Prev_ASSESSMENT_AMT_MAX_UNKNOWN_Index>
					<CFSET Prev_ASSESSMENT_AMT_MAX_UNKNOWN_Word = "[" & ListGetAt(Unknown_NA_List, Prev_ASSESSMENT_AMT_MAX_UNKNOWN_Index) & "]">
				</cfif>

			</cfloop>

			<CFSET Prev_ASSESSMENT_AMOUNT_UPPER_DisplayAmt = Prev_ASSESSMENT_AMT_MAX_UNKNOWN_Word>

		</cfif>

	</cfif>


	<CFIF CONTINGENT_LIAB_GetRecord_PrevRpt.ASSESSMENT_AMT_UPPER_HIGH_END NEQ "">

		<CFSET Prev_ASSESSMENT_AMT_UPPER_HIGH_END_DisplayAmt = CONTINGENT_LIAB_GetRecord_PrevRpt.ASSESSMENT_AMT_UPPER_HIGH_END / 1000000>
		<CFSET Prev_ASSESSMENT_AMT_UPPER_HIGH_END_DisplayAmt = NumberFormat(Prev_ASSESSMENT_AMT_UPPER_HIGH_END_DisplayAmt, '_$__._') & " Million">

	   	<CFSET Prev_ASSESSMENT_AMOUNT_UPPER_DisplayAmt = Prev_ASSESSMENT_AMOUNT_UPPER_DisplayAmt & " - " & Prev_ASSESSMENT_AMT_UPPER_HIGH_END_DisplayAmt>

	</cfif>


</cfif>


