<cfinclude template="MfaCookieCheck.cfm">
<CFQUERY NAME="Get_PrevReportDate" DATASOURCE="ContLiab">

SELECT MAX(DATE_REPORT) AS DATE_REPORT_PREV

FROM CONTINGENT_LIAB_REPORT

WHERE DATE_REPORT <= ADD_MONTHS(SYSDATE, 2)
AND DELETED_FLAG IS NULL

</cfquery>

